from tkinter import *
tk = Tk()
tk.geometry('300x300')
tk.title('Calculator')
tk.configure(bg='grey')
vod1 = Entry()
vod1.pack(pady=15)
vod2 = Entry()
vod2.pack(pady=15)
button1 = Button(text='+', width=10, command=lambda: label.config(text=int(vod1.get()) + int(vod2.get())))
button1.pack(pady=5)
button2 = Button(text='-', width=10, command=lambda: label.config(text=int(vod1.get()) - int(vod2.get())))
button2.pack(pady=5)
button3 = Button(text='*', width=10, command=lambda: label.config(text=int(vod1.get()) * int(vod2.get())))
button3.pack(pady=5)
button4 = Button(text='/', width=10, command=lambda: label.config(text=int(vod1.get()) / int(vod2.get())))
button4.pack(pady=5)
label = Label()
label.pack(pady=10)
tk.mainloop()